-- First, drop the company_locations table and its policies if they exist
DROP TABLE IF EXISTS company_locations CASCADE;

-- Now add the location fields to the companies table
ALTER TABLE companies
ADD COLUMN IF NOT EXISTS address_1 VARCHAR(255),
ADD COLUMN IF NOT EXISTS city_1 VARCHAR(100),
ADD COLUMN IF NOT EXISTS state_1 VARCHAR(50),
ADD COLUMN IF NOT EXISTS is_headquarters_1 BOOLEAN DEFAULT false,

ADD COLUMN IF NOT EXISTS address_2 VARCHAR(255),
ADD COLUMN IF NOT EXISTS city_2 VARCHAR(100),
ADD COLUMN IF NOT EXISTS state_2 VARCHAR(50),
ADD COLUMN IF NOT EXISTS is_headquarters_2 BOOLEAN DEFAULT false,

ADD COLUMN IF NOT EXISTS address_3 VARCHAR(255),
ADD COLUMN IF NOT EXISTS city_3 VARCHAR(100),
ADD COLUMN IF NOT EXISTS state_3 VARCHAR(50),
ADD COLUMN IF NOT EXISTS is_headquarters_3 BOOLEAN DEFAULT false,

ADD COLUMN IF NOT EXISTS address_4 VARCHAR(255),
ADD COLUMN IF NOT EXISTS city_4 VARCHAR(100),
ADD COLUMN IF NOT EXISTS state_4 VARCHAR(50),
ADD COLUMN IF NOT EXISTS is_headquarters_4 BOOLEAN DEFAULT false,

ADD COLUMN IF NOT EXISTS address_5 VARCHAR(255),
ADD COLUMN IF NOT EXISTS city_5 VARCHAR(100),
ADD COLUMN IF NOT EXISTS state_5 VARCHAR(50),
ADD COLUMN IF NOT EXISTS is_headquarters_5 BOOLEAN DEFAULT false,

ADD COLUMN IF NOT EXISTS address_6 VARCHAR(255),
ADD COLUMN IF NOT EXISTS city_6 VARCHAR(100),
ADD COLUMN IF NOT EXISTS state_6 VARCHAR(50),
ADD COLUMN IF NOT EXISTS is_headquarters_6 BOOLEAN DEFAULT false,

ADD COLUMN IF NOT EXISTS address_7 VARCHAR(255),
ADD COLUMN IF NOT EXISTS city_7 VARCHAR(100),
ADD COLUMN IF NOT EXISTS state_7 VARCHAR(50),
ADD COLUMN IF NOT EXISTS is_headquarters_7 BOOLEAN DEFAULT false,

ADD COLUMN IF NOT EXISTS address_8 VARCHAR(255),
ADD COLUMN IF NOT EXISTS city_8 VARCHAR(100),
ADD COLUMN IF NOT EXISTS state_8 VARCHAR(50),
ADD COLUMN IF NOT EXISTS is_headquarters_8 BOOLEAN DEFAULT false,

ADD COLUMN IF NOT EXISTS address_9 VARCHAR(255),
ADD COLUMN IF NOT EXISTS city_9 VARCHAR(100),
ADD COLUMN IF NOT EXISTS state_9 VARCHAR(50),
ADD COLUMN IF NOT EXISTS is_headquarters_9 BOOLEAN DEFAULT false,

ADD COLUMN IF NOT EXISTS address_10 VARCHAR(255),
ADD COLUMN IF NOT EXISTS city_10 VARCHAR(100),
ADD COLUMN IF NOT EXISTS state_10 VARCHAR(50),
ADD COLUMN IF NOT EXISTS is_headquarters_10 BOOLEAN DEFAULT false; 