-- Add transcript support to interview system
-- This migration adds fields to store full conversation transcripts

-- Add transcript fields to interview_sessions table
ALTER TABLE interview_sessions 
ADD COLUMN full_transcript JSONB,
ADD COLUMN conversation_summary TEXT,
ADD COLUMN key_insights JSONB,
ADD COLUMN conversation_metadata JSONB;

-- Add indexes for transcript queries
CREATE INDEX idx_interview_sessions_transcript ON interview_sessions USING GIN (full_transcript);
CREATE INDEX idx_interview_sessions_summary ON interview_sessions (conversation_summary);

-- Add RLS policies for transcript data
CREATE POLICY "Users can view their own interview transcripts" ON interview_sessions
  FOR SELECT USING (intern_id = auth.uid());

CREATE POLICY "Users can update their own interview transcripts" ON interview_sessions
  FOR UPDATE USING (intern_id = auth.uid());

-- Add function to generate transcript summary
CREATE OR REPLACE FUNCTION generate_transcript_summary(transcript_json JSONB)
RETURNS TEXT AS $$
BEGIN
  -- This function will be called by the application to generate summaries
  -- The actual AI processing will happen in the application layer
  RETURN 'Transcript summary will be generated by AI';
END;
$$ LANGUAGE plpgsql;

-- Add trigger to update summary when transcript changes
CREATE OR REPLACE FUNCTION update_transcript_summary()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.full_transcript IS NOT NULL AND NEW.full_transcript != OLD.full_transcript THEN
    NEW.conversation_summary = generate_transcript_summary(NEW.full_transcript);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_transcript_summary
  BEFORE UPDATE ON interview_sessions
  FOR EACH ROW
  EXECUTE FUNCTION update_transcript_summary();

-- Add sample transcript structure
COMMENT ON COLUMN interview_sessions.full_transcript IS 'JSONB structure: {
  "conversation": [
    {
      "timestamp": "10:30:15",
      "speaker": "AI|STUDENT", 
      "content": "text content",
      "metadata": {
        "question_category": "technical|behavioral|experience|interests|goals",
        "response_duration": 30,
        "key_points": ["point1", "point2"],
        "sentiment": "positive|neutral|negative",
        "confidence": 0.85
      }
    }
  ],
  "metadata": {
    "total_turns": 30,
    "total_duration": 1200,
    "ai_speaking_time": 300,
    "student_speaking_time": 900,
    "conversation_flow": "smooth|hesitant|confident"
  }
}';

COMMENT ON COLUMN interview_sessions.conversation_summary IS 'AI-generated summary of the full conversation';
COMMENT ON COLUMN interview_sessions.key_insights IS 'JSONB array of key insights extracted from the conversation';
COMMENT ON COLUMN interview_sessions.conversation_metadata IS 'Additional metadata about the conversation quality and flow'; 